### ISSUE TITLE
贴内回复后显示异常

### ISSUE THREAD

**Issue by jiongjiongJOJO** [ezyshu/UserScript#2]
https://linux.do/t/topic/171874/3

回复完之后，帖子显示了好多条一样的信息，如果瞬间切到其他帖子，这个回复就会带到其他贴子里。（不影响实际数据，只是显示异常）

**Comment by anghunk** [comment]
0.0.27 暂时先停止维护了，已经全部迁移到 https://github.com/dlzmoe/linuxdo-scripts ，我测试下有没有同样的问题
